links:
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1725528
      results:
        - test: custom-highlight-painting-invalidation-002.html
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1727394
      results:
        - test: custom-highlight-painting-iframe-006.html
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1836321
      results:
        - test: css-highlight-painting-underline-offset-001.html
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1861283
      results:
        - test: custom-highlight-font-metrics-002.html
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1874300
      results:
        - test: custom-highlight-container-metrics-001.html
        - test: custom-highlight-container-metrics-003.html
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1875588
      results:
        - test: custom-highlight-dynamic-container-metrics-003.html
        - test: custom-highlight-dynamic-container-metrics-004.html
        - test: custom-highlight-dynamic-font-metrics-001.html
        - test: custom-highlight-dynamic-logical-metrics-001.html
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1703961
      results:
        - test: '*'
